string _ap_formats[19] = {
"<== Starting add_nums LOOP ==>\n",
"============ EVENT %d ============\n",
"main() --> Current index %d \n",
"============ EVENT %d ============\n",
"main() --> Current index %d \n",
"============ EVENT %d ============\n",
"main() --> Current index %d \n",
"============ EVENT %d ============\n",
"main() --> Current index %d \n",
"============ EVENT %d ============\n",
"main() --> Current index %d \n",
"============ EVENT %d ============\n",
"main() --> Current index %d \n",
"fit() --> Best fit param a: %0.6f\n",
"fit() --> Best fit param b: %0.6f\n",
"\tuncertainty on a:  %.6f\n",
"\tuncertainty on b:  %.6f\n",
"fit() --> f(a,b) = %.9f\n",
"fit() --> goodness of fit = %.9f\n"
};